name: CI of the website

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    lint:
        name: Run eslint and build test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: "22.x"
                  cache: "npm"
            - run: node --version
            - name: Install Dependencies
              run: npm install
            - name: Run eslint
              run: npm run lint
            - name: Run build test
              run: npm run build
